include ./themes/frappe.conf

# Settings
enabled_layouts splits,stack

# Visual Settings
enable_audio_bell false

background_opacity 	    0.8
dynamic_background_opacity  yes

tab_bar_style 	      powerline
tab_powerline_style   slanted
tab_title_max_length  16

# Mappings
map ctrl+shift+9 launch --location=vsplit --cwd=current
map ctrl+shift+0 launch --location=hsplit --cwd=current
map ctrl+shift+t launch --type=tab --cwd=current
